VERİ LİSTESİ OLUŞTURMAK İÇİN GREKLİ OLAN KODALR

!pip install faker

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random
from faker import Faker
from datetime import datetime, timedelta

# Türkçe isimler ve veriler oluşturmak için kütüphane
fake = Faker('tr_TR')

# --- Ön Hazırlık Listeleri ---
sehir_listesi = [fake.city() for _ in range(80)]
meslek_listesi = [fake.job() for _ in range(50)]

# Popüler Araba Markaları Havuzu
araba_markalari = ["Fiat", "Renault", "Ford", "Toyota", "Volkswagen", "Hyundai", "Honda", "Opel", "Peugeot", "BMW", "Mercedes"]

# Sigorta Türleri
sigorta_turleri = ["Trafik", "Kasko", "Trafik ve Kasko", "Dask", "Konut", "Dask ve Konut"]

satir_sayisi = 1000
data = []

for _ in range(satir_sayisi):
    # 1. Kişisel Bilgiler
    isim = fake.name()
    sehir = random.choice(sehir_listesi)
    meslek = random.choice(meslek_listesi)

    # 2. Sigorta Türü Seçimi
    sigorta_turu = random.choice(sigorta_turleri)


    # Eğer sigorta türünde Trafik veya Kasko geçiyorsa araba bilgisi ekle, yoksa boş bırak
    if "Trafik" in sigorta_turu or "Kasko" in sigorta_turu:
        araba_markasi = random.choice(araba_markalari)
        araba_yili = random.randint(2005, 2025)
    else:
        araba_markasi = np.nan  # Veri yok anlamında (Not a Number)
        araba_yili = np.nan

    # 4. Fiyatlandırma Mantığı
    if sigorta_turu == "Trafik":
        police_degeri = random.randint(6000, 10000)
    elif sigorta_turu == "Kasko":
        police_degeri = random.randint(8000, 12000)
    elif sigorta_turu == "Trafik ve Kasko":
        police_degeri = random.randint(14000, 22000)
    elif sigorta_turu == "Dask":
        police_degeri = random.randint(5000, 7000)
    elif sigorta_turu == "Konut":
        police_degeri = random.randint(6000, 8000)
    elif sigorta_turu == "Dask ve Konut":
        police_degeri = random.randint(11000, 15000)
    else:
        police_degeri = 0

    # 5. Komisyon
    komisyon_orani = random.randint(8, 20)
    komisyon_tutari = police_degeri * (komisyon_orani / 100)

    # 6. Tarih
    gun_farki = random.randint(0, 365)
    tarih = datetime.now() - timedelta(days=gun_farki)
    tarih_str = tarih.strftime('%d.%m.%Y')

    # 7. Yenileme Yılı
    yenileme = random.randint(0, 10)

    # 8. Referans
    referans_var_mi = random.choices([True, False], weights=[70, 30])[0]
    referans = fake.name() if referans_var_mi else "Yok"

   
    # Önce: Bu kişi poliçeyi satın aldı mı?
    satin_aldi_mi = random.choices([True, False], weights=[85, 15])[0]

    if satin_aldi_mi:
        # Satın aldıysa: İptal etti mi?
        iptal_mi = random.choices([True, False], weights=[20, 80])[0]
        if iptal_mi:
            durum = "İptal Edildi"
        else:
            durum = "Aktif"
    else:
        durum = "Satın Alınmadı" # Teklif aşamasında kalmış

    # Listeye ekle
    data.append([
        isim,
        sehir,
        meslek,
        sigorta_turu,
        araba_markasi,
        araba_yili,    
        police_degeri,
        komisyon_orani,
        round(komisyon_tutari, 2),
        tarih_str,
        yenileme,
        referans,
        durum          
    ])

# DataFrame oluşturma
df = pd.DataFrame(data, columns=[
    'İsim Soyisim',
    'Şehir',
    'Meslek',
    'Sigorta Türü',
    'Araba Markası',
    'Araç Model Yılı',
    'Poliçe Değeri (TL)',
    'Komisyon Oranı (%)',
    'Komisyon Tutarı (TL)',
    'İşlem Tarihi',
    'Yenileme Yılı',
    'Referans',
    'Poliçe Durumu'
])

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
musteriListesi=pd.read_excel("/content/Kod çalışmak için rastgele oluşturulmuş sigorta dosyası (1).xlsx")

In [5]:
musteriListesi

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Araba Markası,Araç Model Yılı,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),İşlem Tarihi,Yenileme Yılı,Referans,Poliçe Durumu
0,Esengün Aynımah Akar,Türkmouth,Tornacı,Dask,NaN,NaN,6253,20,1250.60,19.11.2025,6,Yok,Satın Alınmadı
1,Tomurcuk Gülnaziye Şensoy Dumanlı,East Zülfüyeshire,Pandomimci,Dask,NaN,NaN,5641,10,564.10,24.03.2025,3,Bitül Müret Çetin,Aktif
2,Aksöğüt Alemdar,East Bekbayview,Manikürcü,Trafik,Toyota,2017.0,6425,11,706.75,02.11.2025,3,Kelâmi Şafak,Satın Alınmadı
3,Nurveren Selçuk Zorlu,Kalgaymouth,Tornacı,Konut,NaN,NaN,7502,10,750.20,16.05.2025,7,Dr. Gülşeref Karadeniz Soylu,Aktif
4,Okt. Görsev Arsoy İnönü,East Şadımanside,İşletme mühendisi,Kasko,Honda,2020.0,11137,16,1781.92,01.08.2025,0,Yok,Satın Alınmadı
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Çev. Ballı Gülbiye İhsanoğlu Gülen,Lake Gülnaziye,Meteoroloji uzmanı,Konut,NaN,NaN,6865,20,1373.00,29.08.2025,1,Dirlik Aru Zengin Ertaş,İptal Edildi
996,Kutun Sakarya,Kalgaymouth,İşletme mühendisi,Dask ve Konut,NaN,NaN,13969,17,2374.73,01.10.2025,0,Müsemma Şener Şensoy,İptal Edildi
997,Av. Vefia Demirel Duran,Ergülfurt,Radyolog,Dask,NaN,NaN,5370,18,966.60,01.12.2025,0,Yok,Aktif
998,Nazende Akdeniz,Sılaburgh,Piyanist,Trafik,Fiat,2014.0,7780,16,1244.80,02.11.2025,5,Yok,Satın Alınmadı
999,Firdevis Akgündüz Bilge,Akgündüzmouth,Boyacı,Dask ve Konut,NaN,NaN,11646,9,1048.14,10.09.2025,7,Yok,Satın Alınmadı

In [6]:
musteriListesi.describe().T #.484 tanesi araç sigortası.

,count,mean,std,min,25%,50%,75%,max
Araç Model Yılı,484.0,2015.123967,6.249234,2005.00,2010.0000,2015.000,2021.00,2025.00
Poliçe Değeri (TL),1000.0,10321.138000,4215.186129,5013.00,6827.0000,8957.000,13234.75,21968.00
Komisyon Oranı (%),1000.0,13.714000,3.754237,8.00,10.0000,14.000,17.00,20.00
Komisyon Tutarı (TL),1000.0,1423.285010,734.421295,401.92,870.8625,1236.295,1784.49,4171.64
Yenileme Yılı,1000.0,4.820000,3.096642,0.00,2.0000,5.000,7.00,10.00

In [11]:
musteriListesi.columns

Index(['İsim Soyisim', 'Şehir', 'Meslek', 'Sigorta Türü', 'Araba Markası',
       'Araç Model Yılı', 'Poliçe Değeri (TL)', 'Komisyon Oranı (%)',
       'Komisyon Tutarı (TL)', 'İşlem Tarihi', 'Yenileme Yılı', 'Referans',
       'Poliçe Durumu'],
      dtype='object')

In [ ]:
musteriListesiKodları={
    "Trafik":1,
    "Kasko":2,

}